package helpers

import (
	"encoding/json"
	"faceitAI/src/models"
	"faceitAI/src/models/dto"
)

func BuildMatch(matchId string, data []byte) models.Match {
	var matchDto dto.AutoGeneratedDto
	var match models.Match
	json.Unmarshal(data, &matchDto)

	match.Map = matchDto[0].I1

	return match
}
